version: 3

services:
  pelican:
    build: .
    container_name: pelican
    ports:
      - 8080:80
    volumes:
      - ./pelican/project:~/pelican
      - ./pelican/nginx:/usr/share/nginx/html
    restart: always

volumes:
  pelican: {}
